# Helper to generate a list of all of the HTML elements supported by modern browsers.
# Little bit of manual work here to copy stdout in to the html.py file whilst
# I work out a better way to handle this.

html_list = [
    ("a",),
    ("abbr",),
    ("address",),
    ("area", True),
    ("article",),
    ("aside",),
    ("audio",),
    ("base", True),
    ("blockquote",),
    ("body",),
    ("br", True),
    ("button",),
    ("canvas",),
    ("caption",),
    ("circle",),
    ("cite",),
    ("code",),
    ("col", True),
    ("colgroup",),
    ("data",),
    ("datalist",),
    ("dd",),
    ("del_",),
    ("details",),
    ("dialog",),
    ("div",),
    ("dl",),
    ("dt",),
    ("ellipse",),
    ("em",),
    ("embed", True),
    ("fieldset",),
    ("figcaption",),
    ("figure",),
    ("footer",),
    ("form",),
    ("h1",),
    ("h2",),
    ("h3",),
    ("h4",),
    ("h5",),
    ("h6",),
    ("head",),
    ("header",),
    ("hr", True),
    ("html",),
    ("iframe",),
    ("img", True),
    ("input", True),
    ("kbd",),
    ("label",),
    ("legend",),
    ("li",),
    ("link", True),
    ("main",),
    ("map",),
    ("mark",),
    ("menu",),
    ("meta", True),
    ("meter",),
    ("nav",),
    ("noscript",),
    ("ol",),
    ("optgroup",),
    ("option",),
    ("output",),
    ("p",),
    ("picture",),
    ("polygon",),
    ("portal",),
    ("pre",),
    ("progress",),
    ("param", True),
    ("q",),
    ("rect",),
    ("s",),
    ("samp",),
    ("script",),
    ("section",),
    ("select",),
    ("slot",),
    ("small",),
    ("source", True),
    ("span",),
    ("strong",),
    ("style",),
    ("sub",),
    ("summary",),
    ("sup",),
    ("svg",),
    ("table",),
    ("tbody",),
    ("td",),
    ("template",),
    ("text",),
    ("textarea",),
    ("tfoot",),
    ("th",),
    ("thead",),
    ("time",),
    ("title",),
    ("tr",),
    ("track", True),
    ("u",),
    ("ul",),
    ("var",),
    ("video",),
    ("wbr", True),
]


def create_elements(html_list: set) -> None:
    for html_element in html_list:
        el, *tag = html_element
        end_tag = False if tag else True
        print(f"{el} = _el_factory('{el}', end_tag={end_tag})")


create_elements(html_list)
